site_name: TALLY NODE
site_description: ESP32-S3 기반 무선 Tally 시스템
site_author: TALLY NODE Team
site_url: https://username.github.io/TALLY_NODE

# Repository
repo_name: TALLY_NODE
repo_url: https://github.com/username/TALLY_NODE

# Copyright
copyright: Copyright &copy; 2024 TALLY NODE Team

theme:
  name: material
  language: ko
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.action.edit
  
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: ko
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: username
      repo: TALLY_NODE
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - 홈: index.md
  - 하드웨어:
    - hardware/overview.md
    - hardware/specifications.md
    - hardware/assembly.md
  - 펌웨어:
    - firmware/installation.md
    - firmware/configuration.md
    - firmware/upload.md
    - firmware/api.md
  - 서버:
    - server/setup.md
    - server/api-reference.md
    - server/database.md
  - 가이드:
    - guides/quickstart.md
    - guides/troubleshooting.md
    - guides/examples.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username/TALLY_NODE
  version:
    provider: mike

# Custom CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/esp-web-tools@10.0.1/dist/web/install-button.js

# Files to include in the build
use_directory_urls: true