name: 문서 배포

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'manifest_*.json'
      - 'data/**'
      - '.github/workflows/docs.yml'
  
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

  # 수동 실행 허용
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포를 허용하지 않음 (진행 중인 실행 취소하지 않음)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 문서 빌드 작업
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
        
    - name: 의존성 설치
      run: |
        pip install --upgrade pip
        pip install mkdocs-material
        pip install mkdocs-git-revision-date-localized-plugin
        
    - name: MkDocs 빌드
      run: mkdocs build --verbose --clean
      
    - name: 펌웨어 파일 복사
      run: |
        # manifest 파일들을 site 루트로 복사
        cp manifest_*.json site/
        
        # data 폴더를 site로 복사  
        cp -r data site/
        
        # index.html 백업 파일도 복사 (필요시)
        cp index.html site/index_backup.html
        
    - name: GitHub Pages 업로드
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site

  # 배포 작업
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: GitHub Pages 배포
      id: deployment
      uses: actions/deploy-pages@v4